"""Small shared helpers used across screens and modules."""

from __future__ import annotations

# Fixed wizard step labels, used for the "Step N/M: ..." breadcrumb shown
# in each screen's title. Steps 3 (OS) and 4 (image) are sometimes
# auto-skipped when a narrower choice leaves only one match, but the
# ordinal numbering stays stable so the breadcrumb still reads as
# progress rather than resetting.
STEP_LABELS = (
    "Select disk",
    "Select Pi model",
    "Select OS",
    "Select image",
    "Options",
    "User account",
    "WLAN details",
    "Confirm",
    "Flashing",
)

# Named ordinals for the STEP_LABELS entries above, so each screen passes
# a self-documenting name to step_title() instead of a bare integer --
# reordering/inserting a step only needs updating this block plus
# STEP_LABELS, rather than hunting down every step_title(N) call site.
(
    STEP_DISK,
    STEP_DEVICE,
    STEP_OS,
    STEP_IMAGE,
    STEP_OPTIONS,
    STEP_USER_DETAILS,
    STEP_WLAN_DETAILS,
    STEP_CONFIRM,
    STEP_FLASHING,
) = range(1, len(STEP_LABELS) + 1)


def step_title(step: int) -> str:
    return f"Step {step}/{len(STEP_LABELS)}: {STEP_LABELS[step - 1]}"


# The exact set raspi-config's `do_wifi_country` validates a WLAN country
# code against (`/usr/share/zoneinfo/iso3166.tab` on the Pi) -- also used
# as the CRDA regulatory domain. A 2-letter code that isn't in this list
# (a common mistake: "UK" instead of "GB" for the United Kingdom) fails
# that validation on first boot; `raspberrypi-sys-mods`' init_config only
# logs the failure, so the Wi-Fi radio is left rfkill-blocked with no
# visible error at all. Validating here catches the mistake before it
# ever reaches the card.
WIFI_COUNTRY_CODES = frozenset(
    [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW",
    ]
)


def valid_wifi_country(code: str) -> bool:
    return code.upper() in WIFI_COUNTRY_CODES


def human_bytes(n: int) -> str:
    value = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return (
                f"{value:.0f} {unit}" if unit == "B" else f"{value:.1f} {unit}"
            )
        value /= 1024
    return f"{value:.1f} TB"
